using System;

namespace SettingsForTV.WindowScrape.Constants;

[Flags]
internal enum PositioningFlags
{
    SWP_ASYNCWINDOWPOS = 0x4000,
    SWP_DEFERERASE = 0x2000,
    SWP_DRAWFRAME = 0x20,
    SWP_FRAMECHANGED = 0x20,
    SWP_HIDEWINDOW = 0x80,
    SWP_NOACTIVATE = 0x10,
    SWP_NOCOPYBITS = 0x100,
    SWP_NOMOVE = 2,
    SWP_NOOWNERZORDER = 0x200,
    SWP_NOREDRAW = 8,
    SWP_NOREPOSITION = 0x200,
    SWP_NOSENDCHANGING = 0x400,
    SWP_NOSIZE = 1,
    SW_SHOWNORMAL = 1,
    SWP_NOZORDER = 4,
    SWP_SHOWWINDOW = 0x40
}

public enum DeviceCap
{
    VERTRES = 10,
    DESKTOPVERTRES = 117
}

public enum SE_OBJECT_TYPE
{
    SE_UNKNOWN_OBJECT_TYPE,
    SE_FILE_OBJECT,
    SE_SERVICE,
    SE_PRINTER,
    SE_REGISTRY_KEY,
    SE_LMSHARE,
    SE_KERNEL_OBJECT,
    SE_WINDOW_OBJECT,
    SE_DS_OBJECT,
    SE_DS_OBJECT_ALL,
    SE_PROVIDER_DEFINED_OBJECT,
    SE_WMIGUID_OBJECT,
    SE_REGISTRY_WOW64_32KEY
}

public enum SECURITY_INFORMATION
{
    OWNER_SECURITY_INFORMATION = 1,
    GROUP_SECURITY_INFORMATION = 2,
    DACL_SECURITY_INFORMATION = 4,
    SACL_SECURITY_INFORMATION = 8
}